version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: jobdeal_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=jobdeal
      - MYSQL_USER=jobdeal
      - MYSQL_PASSWORD=password
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - db-data:/var/lib/mysql

  app:
    container_name: jobdeal_app
    build:
      context: .docker
      args:
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
    working_dir: /var/www/${USERNAME}
    # entrypoint: /var/www/${USERNAME}/.docker/setup.sh
    volumes:
      - ./:/var/www/jobdeal

  redis:
    image: redis:7-alpine
    container_name: jobdeal_redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  db-data:
  redis-data: